// Assistant local, isolé et personnalisé selon le rôle JWT.
import { useEffect,useRef,useState,type FormEvent } from 'react'
import { Bot,MessageCircle,Plus,Send,Trash2,X } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { api } from '../lib/api'
import { useAuth } from '../store/auth'
import { ChatErrorBoundary } from './ChatErrorBoundary'
interface Action{label:string;path?:string;message?:string}
interface PreviewItem{product_id:number;reference:string;name:string;quantity:number;unit_price:number;line_total:number}
interface Preview{supplier?:string;items?:PreviewItem[];estimated_total?:number;warning?:string}
interface Reply{type:'answer'|'confirmation_required'|'action_completed'|'cancelled'|'error';message:string;data?:unknown;suggested_navigation?:string;action?:string;confirmation_token?:string;preview?:Preview}
interface Message{side:'user'|'assistant';text:string;actions?:Action[];token?:string;preview?:Preview;resolved?:boolean}
const welcomes={client:'Bonjour, je peux vous aider à rechercher un produit et consulter uniquement vos commandes.',achats:'Bonjour, je peux vous aider à consulter les commandes clients, les achats fournisseurs et le stock.',admin:'Bonjour, je peux vous aider à consulter les utilisateurs, les produits et les statistiques.'}
const suggestions:Record<string,Action[]>={admin:[['Combien d’utilisateurs ?','Combien d’utilisateurs ?'],['Combien de produits ?','Combien de produits ?'],['Comptes en attente','Combien de comptes clients sont en attente ?'],['Résumé','Résumé du tableau de bord']].map(([label,message])=>({label,message})),achats:[['Commandes à traiter','Commandes clients à traiter'],['Achats à réceptionner','Achats à réceptionner'],['Stock faible','Produits en stock faible'],['Fournisseur','Rechercher un fournisseur']].map(([label,message])=>({label,message})),client:[['Rechercher un produit','Rechercher un produit'],['Mes commandes','Mes commandes'],['Dernière commande','Statut de ma dernière commande'],['Comment commander ?','Comment passer une commande ?']].map(([label,message])=>({label,message}))}
export function ChatWidget(){return <ChatErrorBoundary><ChatContent/></ChatErrorBoundary>}
function ChatContent(){
 const user=useAuth(s=>s.user),navigate=useNavigate(),[open,setOpen]=useState(false),[messages,setMessages]=useState<Message[]>([]),[value,setValue]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),end=useRef<HTMLDivElement>(null),mounted=useRef(true),request=useRef<AbortController|null>(null),welcome=user?welcomes[user.role]:''
 const greeting=():Message=>({side:'assistant',text:welcome,actions:user?suggestions[user.role]:[]})
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;request.current?.abort();request.current=null}},[])
 useEffect(()=>{if(open&&!messages.length)setMessages([greeting()])},[open,messages.length,welcome])
 useEffect(()=>{end.current?.scrollIntoView({behavior:'smooth'})},[messages,busy])
 const sendMessage=async(raw:string)=>{const message=raw.trim();if(!message||busy)return;request.current?.abort();const controller=new AbortController();request.current=controller;setMessages(items=>[...items,{side:'user',text:message}]);setValue('');setBusy(true);setError('');try{const {data}=await api.post<Reply>('/agent/message',{message},{signal:controller.signal});if(mounted.current&&!controller.signal.aborted)setMessages(items=>[...items,{side:'assistant',text:data.message,actions:data.suggested_navigation?[{label:'Ouvrir',path:data.suggested_navigation}]:undefined,token:data.confirmation_token,preview:data.preview}])}catch(err:any){if(mounted.current&&!controller.signal.aborted)setError(err.response?.status===401?'Votre session a expiré. Veuillez vous reconnecter.':err.response?.data?.detail||'Le serveur local ne répond pas. Réessayez dans un instant.')}finally{if(mounted.current&&!controller.signal.aborted)setBusy(false);if(request.current===controller)request.current=null}}
 const submit=(e:FormEvent)=>{e.preventDefault();void sendMessage(value)}
 const reset=async()=>{request.current?.abort();request.current=null;setBusy(false);try{await api.delete('/chatbot/history')}catch{}if(mounted.current){setMessages([greeting()]);setError('')}}
 const runAction=(action:Action)=>{if(action.path){navigate(action.path);setOpen(false)}else if(action.message)void sendMessage(action.message)}
 const decide=async(index:number,confirm:boolean)=>{const target=messages[index];if(!target.token||busy)return;setBusy(true);setError('');try{const {data}=await api.post<Reply>(confirm?'/agent/confirm':'/agent/cancel',{confirmation_token:target.token});if(mounted.current){setMessages(items=>items.map((item,i)=>i===index?{...item,resolved:true}:item).concat({side:'assistant',text:data.message,actions:data.suggested_navigation?[{label:'Ouvrir le brouillon',path:data.suggested_navigation}]:undefined}));}}catch(err:any){if(mounted.current)setError(err.response?.data?.detail||'Cette proposition ne peut plus être utilisée.')}finally{if(mounted.current)setBusy(false)}}
 return <><button className={`chat-launcher ${open?'is-open':''}`} onClick={()=>setOpen(x=>!x)} aria-label={open?'Fermer l’assistant':'Ouvrir l’assistant'}>{open?<X size={24}/>:<MessageCircle size={25}/>}<span>Assistant</span></button>{open&&<section className="chat-panel" aria-label="Assistant SOREMED"><header className="chat-header"><div className="chat-bot-mark"><Bot size={22}/></div><div><strong>Agent métier SOREMED</strong><span><i/>En ligne · service local</span></div><button onClick={()=>void reset()} title="Nouvelle conversation"><Plus size={19}/></button><button onClick={()=>setOpen(false)} title="Fermer"><X size={19}/></button></header><div className="chat-messages">{messages.map((m,i)=><div key={i} className={`chat-message ${m.side}`}><div>{m.text}</div>{m.preview&&<div className="chat-preview"><b>Fournisseur : {m.preview.supplier||'Non associé'}</b>{m.preview.items?.map(item=><div key={item.product_id}>{item.name} · {item.quantity} × {item.unit_price.toFixed(2)} MAD</div>)}<strong>Total estimé : {Number(m.preview.estimated_total||0).toFixed(2)} MAD</strong><small>{m.preview.warning}</small></div>}{m.token&&!m.resolved&&<div className="chat-actions"><button disabled={busy} onClick={()=>void decide(i,true)}>Confirmer</button><button disabled={busy} onClick={()=>void decide(i,false)}>Annuler</button></div>}{m.actions?.length?<div className="chat-actions">{m.actions.map(a=><button key={`${a.path||''}-${a.message||a.label}`} onClick={()=>runAction(a)}>{a.label}</button>)}</div>:null}</div>)}{busy&&<div className="chat-message assistant chat-typing"><i/><i/><i/></div>}{error&&<div className="chat-error">{error}</div>}<div ref={end}/></div><form className="chat-compose" onSubmit={submit}><input value={value} onChange={e=>setValue(e.target.value)} placeholder="Écrivez votre question…" maxLength={1000} disabled={busy}/><button disabled={busy||!value.trim()} aria-label="Envoyer"><Send size={18}/></button></form><footer><button onClick={()=>void reset()}><Trash2 size={13}/>Nouvelle conversation</button><span>Aucune API Internet utilisée</span></footer></section>}</>
}
