// Petits composants visuels réutilisables par les écrans métier.
import type { ReactNode } from 'react'
import { AlertTriangle, CheckCircle2, X } from 'lucide-react'
export function PageHeader({title,subtitle,action}:{title:string;subtitle:string;action?:ReactNode}) { return <div className="page-heading"><div><span className="page-eyebrow">Espace de gestion</span><h2>{title}</h2><p>{subtitle}</p></div>{action&&<div className="page-actions">{action}</div>}</div> }
export function Badge({children,tone='green'}:{children:ReactNode;tone?:'green'|'red'|'blue'|'gray'|'amber'}) { const colors={green:'badge-green',red:'badge-red',blue:'badge-blue',gray:'badge-gray',amber:'badge-amber'};return <span className={`status-badge ${colors[tone]}`}>{children}</span> }
export function Modal({title,children,onClose}:{title:string;children:ReactNode;onClose:()=>void}) { return <div className="modal-backdrop"><div className="modal-panel"><div className="modal-heading"><div><span>Plateforme SOREMED</span><h3>{title}</h3></div><button onClick={onClose} aria-label="Fermer"><X size={20}/></button></div><div className="modal-content">{children}</div></div></div> }
export function Empty({text='Aucune donnée disponible'}:{text?:string}) { return <div className="empty-state"><div className="empty-state-mark">S</div><strong>Aucun résultat</strong><span>{text}</span></div> }
export function Loading() { return <div className="loading-state"><div/><span>Chargement des données…</span></div> }
export function Confirm({title,message,onCancel,onConfirm,busy=false}:{title:string;message:string;onCancel:()=>void;onConfirm:()=>void;busy?:boolean}) { return <div className="fixed inset-0 z-[60] flex items-center justify-center bg-slate-900/50 p-4"><div className="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl"><AlertTriangle className="mb-4 text-amber-500" size={32}/><h3 className="text-lg font-bold text-navy-900">{title}</h3><p className="my-3 text-sm text-slate-600">{message}</p><div className="flex justify-end gap-3"><button className="btn-secondary" onClick={onCancel}>Annuler</button><button className="rounded-lg bg-red-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-red-700" disabled={busy} onClick={onConfirm}>{busy?'Suppression…':'Confirmer'}</button></div></div></div> }
export function Notice({message,type='success',onClose}:{message:string;type?:'success'|'error';onClose:()=>void}) { return <div className={`fixed right-4 top-24 z-[70] flex max-w-sm items-center gap-3 rounded-xl border bg-white p-4 shadow-xl ${type==='error'?'border-red-200 text-red-700':'border-emerald-200 text-emerald-700'}`}>{type==='success'?<CheckCircle2 size={20}/>:<AlertTriangle size={20}/>}<span className="text-sm font-medium">{message}</span><button onClick={onClose}><X size={16}/></button></div> }
