/** Catalogue premium de l'espace client, fondé exclusivement sur les données produits réelles. */
import { useEffect, useMemo, useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { ArrowDownAZ, Check, ChevronLeft, ChevronRight, GitCompareArrows, Grid2X2, Heart, List, PackageOpen, Search, Share2, ShoppingCart, Sparkles, X } from 'lucide-react'
import { api } from '../lib/api'
import { useNavigate, useParams, useSearchParams } from 'react-router-dom'
import { useCart } from '../store/cart'
import type { Category, Product } from '../types'
import { Badge, Empty, Loading, Modal, Notice } from '../components/UI'

type CatalogProduct=Product&{laboratory?:string;dosage?:string;pharmaceutical_form?:string;packaging?:string;old_price?:number;is_new?:boolean;is_promotion?:boolean}
type ViewMode='grid'|'list'
const PAGE_SIZE=24
const money=(value:number)=>Number(value).toLocaleString('fr-MA',{minimumFractionDigits:2,maximumFractionDigits:2})
const readIds=(key:string)=>{try{return JSON.parse(localStorage.getItem(key)||'[]') as number[]}catch{return []}}
const stockState=(product:Product)=>product.stock===0?'out':product.stock<=product.minimum_stock?'low':'available'
const categoryImage=(category:string)=>{const value=category.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();if(value.includes('cardio'))return'/categories/cardiologie.svg';if(value.includes('antibiot'))return'/categories/antibiotique.svg';if(value.includes('diab'))return'/categories/diabete.svg';if(value.includes('digest')||value.includes('gastro'))return'/categories/digestif.svg';if(value.includes('dermat'))return'/categories/dermatologie.svg';if(value==='orl'||value.includes('nasal'))return'/categories/orl.svg';if(value.includes('allerg'))return'/categories/allergie.svg';if(value.includes('ophtal'))return'/categories/ophtalmologie.svg';if(value.includes('vitamin'))return'/categories/vitamines.svg';if(value.includes('hygiene')||value.includes('desinfect'))return'/categories/hygiene.svg';if(value.includes('consomm'))return'/categories/consommables.svg';if(value.includes('materiel')||value.includes('medical'))return'/categories/materiel-medical.svg';return'/categories/divers.svg'}

export default function ClientCatalog(){
  const {id}=useParams(),navigate=useNavigate(),[urlParams]=useSearchParams()
  const add=useCart(s=>s.add),[q,setQ]=useState(''),[category,setCategory]=useState(''),[laboratory,setLaboratory]=useState(''),[availability,setAvailability]=useState(''),[dosage,setDosage]=useState(''),[form,setForm]=useState(''),[minPrice,setMinPrice]=useState(''),[maxPrice,setMaxPrice]=useState(''),[sort,setSort]=useState('name'),[view,setView]=useState<ViewMode>('grid'),[page,setPage]=useState(1),[selected,setSelected]=useState<CatalogProduct|null>(null),[notice,setNotice]=useState<string|null>(null),[favorites,setFavorites]=useState<number[]>(()=>readIds('soremed-favorites')),[compare,setCompare]=useState<number[]>(()=>readIds('soremed-compare')),[history,setHistory]=useState<number[]>(()=>readIds('soremed-view-history'))
  const products=useQuery({queryKey:['client-products-catalog'],queryFn:()=>api.get<CatalogProduct[]>('/products').then(r=>r.data),staleTime:60000}),categories=useQuery({queryKey:['client-categories'],queryFn:()=>api.get<Category[]>('/categories').then(r=>r.data),staleTime:300000})
  useEffect(()=>{const requested=Number(id);if(requested&&products.data){const product=products.data.find(p=>p.id===requested);if(product)setSelected(product)}},[id,products.data])
  useEffect(()=>{const requested=urlParams.get('category');if(requested)setCategory(requested)},[urlParams])
  const categoryName=(id?:number)=>categories.data?.find(c=>c.id===id)?.name||'Sans catégorie'
  const metadata=useMemo(()=>{const list=products.data||[],unique=(values:(string|undefined)[])=>[...new Set(values.filter(Boolean) as string[])].sort((a,b)=>a.localeCompare(b,'fr'));return {laboratories:unique(list.map(p=>p.laboratory)),dosages:unique(list.map(p=>p.dosage)),forms:unique(list.map(p=>p.pharmaceutical_form))}},[products.data])
  const filtered=useMemo(()=>{const term=q.trim().toLocaleLowerCase('fr');return (products.data||[]).filter(p=>{const haystack=[p.commercial_name,p.name,p.active_ingredient,p.reference,p.barcode,p.laboratory,p.dosage,p.pharmaceutical_form,categoryName(p.category_id)].filter(Boolean).join(' ').toLocaleLowerCase('fr');const state=stockState(p);return (!term||haystack.includes(term))&&(!category||String(p.category_id)===category)&&(!laboratory||p.laboratory===laboratory)&&(!availability||state===availability)&&(!dosage||p.dosage===dosage)&&(!form||p.pharmaceutical_form===form)&&(!minPrice||Number(p.price)>=Number(minPrice))&&(!maxPrice||Number(p.price)<=Number(maxPrice))}).sort((a,b)=>sort==='price-asc'?Number(a.price)-Number(b.price):sort==='price-desc'?Number(b.price)-Number(a.price):sort==='new'?new Date(b.created_at).getTime()-new Date(a.created_at).getTime():a.name.localeCompare(b.name,'fr'))},[products.data,q,category,laboratory,availability,dosage,form,minPrice,maxPrice,sort,categories.data])
  const totalPages=Math.max(1,Math.ceil(filtered.length/PAGE_SIZE)),visible=filtered.slice((page-1)*PAGE_SIZE,page*PAGE_SIZE),all=products.data||[],newCount=all.filter(p=>p.is_new||Date.now()-new Date(p.created_at).getTime()<30*86400000).length,availabilityRate=all.length?Math.round(all.filter(p=>p.stock>0).length/all.length*100):0
  const changeFilter=(setter:(value:string)=>void)=>(value:string)=>{setter(value);setPage(1)}
  const persist=(key:string,ids:number[])=>localStorage.setItem(key,JSON.stringify(ids))
  const toggleFavorite=(id:number)=>setFavorites(current=>{const removing=current.includes(id),next=removing?current.filter(x=>x!==id):[...current,id];persist('soremed-favorites',next);void (removing?api.delete(`/favorites/${id}`):api.post(`/favorites/${id}`)).catch(error=>console.error('Synchronisation favori impossible',error));return next})
  const toggleCompare=(id:number)=>setCompare(current=>{if(!current.includes(id)&&current.length>=3){setNotice('Vous pouvez comparer jusqu’à 3 produits.');return current}const next=current.includes(id)?current.filter(x=>x!==id):[...current,id];persist('soremed-compare',next);return next})
  const openProduct=(product:CatalogProduct)=>{setSelected(product);setHistory(current=>{const next=[product.id,...current.filter(id=>id!==product.id)].slice(0,8);persist('soremed-view-history',next);return next})}
  const addProduct=(product:CatalogProduct)=>{if(product.stock<1)return;add(product);setNotice(`${product.name} ajouté au panier.`)}
  const reset=()=>{setQ('');setCategory('');setLaboratory('');setAvailability('');setDosage('');setForm('');setMinPrice('');setMaxPrice('');setSort('name');setPage(1)}
  const similar=selected?all.filter(p=>p.id!==selected.id&&p.category_id===selected.category_id).slice(0,4):[]
  const viewed=history.map(id=>all.find(p=>p.id===id)).filter(Boolean) as CatalogProduct[]
  return <div className="catalog-page"><section className="catalog-hero"><div><span className="catalog-kicker"><Sparkles size={15}/>Catalogue professionnel</span><h1>Nos produits</h1><p>Parcourez notre sélection, vérifiez la disponibilité et préparez votre commande en quelques instants.</p></div><div className="catalog-stats"><CatalogStat value={all.length} label="Produits"/><CatalogStat value={categories.data?.length||0} label="Catégories"/><CatalogStat value={newCount} label="Nouveautés"/><CatalogStat value={`${availabilityRate} %`} label="Disponibles"/></div></section>
    <section className="catalog-toolbar"><div className="catalog-search"><Search size={21}/><input aria-label="Rechercher dans le catalogue" value={q} onChange={e=>changeFilter(setQ)(e.target.value)} placeholder="Nom, référence, laboratoire, catégorie ou code-barres…"/>{q&&<button aria-label="Effacer la recherche" onClick={()=>changeFilter(setQ)('')}><X size={17}/></button>}</div><div className="catalog-view" aria-label="Mode d’affichage"><button className={view==='grid'?'active':''} aria-label="Affichage en grille" onClick={()=>setView('grid')}><Grid2X2 size={18}/></button><button className={view==='list'?'active':''} aria-label="Affichage en liste" onClick={()=>setView('list')}><List size={19}/></button></div></section>
    <div className="catalog-layout"><aside className="catalog-filters"><div className="catalog-filter-heading"><div><b>Filtres</b><span>{filtered.length} résultat(s)</span></div><button onClick={reset}>Réinitialiser</button></div><Filter label="Catégorie" value={category} set={changeFilter(setCategory)} options={(categories.data||[]).map(x=>[String(x.id),x.name])}/><Filter label="Laboratoire" value={laboratory} set={changeFilter(setLaboratory)} options={metadata.laboratories.map(x=>[x,x])}/><Filter label="Disponibilité" value={availability} set={changeFilter(setAvailability)} options={[["available","Disponible"],["low","Stock faible"],["out","Rupture"]]}/><div className="catalog-filter"><label>Prix (MAD)</label><div className="catalog-price"><input type="number" min="0" value={minPrice} onChange={e=>changeFilter(setMinPrice)(e.target.value)} placeholder="Min"/><input type="number" min="0" value={maxPrice} onChange={e=>changeFilter(setMaxPrice)(e.target.value)} placeholder="Max"/></div></div><Filter label="Dosage" value={dosage} set={changeFilter(setDosage)} options={metadata.dosages.map(x=>[x,x])}/><Filter label="Forme pharmaceutique" value={form} set={changeFilter(setForm)} options={metadata.forms.map(x=>[x,x])}/><div className="catalog-filter"><label>Trier par</label><select value={sort} onChange={e=>changeFilter(setSort)(e.target.value)}><option value="name">Nom A–Z</option><option value="price-asc">Prix croissant</option><option value="price-desc">Prix décroissant</option><option value="new">Nouveautés</option></select></div>{compare.length>0&&<div className="compare-box"><GitCompareArrows size={18}/><div><b>{compare.length} produit(s)</b><span>Comparaison sélectionnée</span></div><button onClick={()=>{setCompare([]);persist('soremed-compare',[])}}>Effacer</button></div>}</aside>
      <main className="catalog-results">{products.isLoading||categories.isLoading?<Loading/>:visible.length?<><div className={view==='grid'?'product-premium-grid':'product-premium-list'}>{visible.map(product=><ProductCard key={product.id} product={product} category={categoryName(product.category_id)} view={view} favorite={favorites.includes(product.id)} comparing={compare.includes(product.id)} onFavorite={()=>toggleFavorite(product.id)} onCompare={()=>toggleCompare(product.id)} onView={()=>openProduct(product)} onAdd={()=>addProduct(product)}/>)}</div><div className="catalog-pagination"><span>Page {page} sur {totalPages}</span><div><button disabled={page===1} onClick={()=>{setPage(p=>p-1);scrollTo({top:0,behavior:'smooth'})}}><ChevronLeft size={18}/>Précédent</button><button disabled={page===totalPages} onClick={()=>{setPage(p=>p+1);scrollTo({top:0,behavior:'smooth'})}}>Suivant<ChevronRight size={18}/></button></div></div></>:<div className="catalog-empty"><PackageOpen size={48}/><Empty text="Aucun produit ne correspond à vos critères."/><button className="btn-secondary" onClick={reset}>Effacer les filtres</button></div>}
      {viewed.length>0&&<section className="recent-products"><div><span>Votre historique</span><h2>Consultés récemment</h2></div><div>{viewed.slice(0,5).map(p=><button key={p.id} onClick={()=>openProduct(p)}><ProductVisual product={p} category={categoryName(p.category_id)}/><span><b>{p.name}</b><small>{money(Number(p.price))} MAD</small></span></button>)}</div></section>}</main></div>
    {selected&&<ProductDetails product={selected} category={categoryName(selected.category_id)} similar={similar} onClose={()=>{setSelected(null);if(id)navigate('/client/products',{replace:true})}} onAdd={()=>addProduct(selected)} onSelect={openProduct}/>} {notice&&<Notice message={notice} onClose={()=>setNotice(null)}/>}</div>
}

function CatalogStat({value,label}:{value:string|number;label:string}){return <div><strong>{value}</strong><span>{label}</span></div>}
function Filter({label,value,set,options}:{label:string;value:string;set:(value:string)=>void;options:string[][]}){return <div className="catalog-filter"><label>{label}</label><select value={value} onChange={e=>set(e.target.value)}><option value="">Tous</option>{options.map(([id,name])=><option value={id} key={id}>{name}</option>)}</select>{options.length===0&&<small>Non renseigné dans le catalogue</small>}</div>}
function ProductVisual({product,category}:{product:CatalogProduct;category:string}){const source=product.photo_path||categoryImage(category);return <div className={`product-visual category-${(product.category_id||0)%5}`}><img src={source} alt={product.photo_path?product.commercial_name||product.name:''} loading="lazy" decoding="async"/></div>}
function ProductCard({product,category,view,favorite,comparing,onFavorite,onCompare,onView,onAdd}:{product:CatalogProduct;category:string;view:ViewMode;favorite:boolean;comparing:boolean;onFavorite:()=>void;onCompare:()=>void;onView:()=>void;onAdd:()=>void}){const state=stockState(product),promotion=product.is_promotion&&product.old_price&&product.old_price>product.price,title=product.commercial_name||product.name;return <article className={`premium-product-card ${view}`}><div className="product-media"><ProductVisual product={product} category={category}/><div className="product-badges">{(product.is_new||Date.now()-new Date(product.created_at).getTime()<30*86400000)&&<span className="badge-new">Nouveau</span>}{promotion&&<span className="badge-promo">Promotion</span>}{state==='low'&&<span className="badge-low">Stock faible</span>}</div><div className="product-quick-actions"><button className={favorite?'active':''} aria-label="Ajouter aux favoris" onClick={onFavorite}><Heart size={17} fill={favorite?'currentColor':'none'}/></button><button className={comparing?'active':''} aria-label="Comparer" onClick={onCompare}><GitCompareArrows size={17}/></button><button aria-label="Partager" onClick={()=>void navigator.clipboard?.writeText(window.location.href)}><Share2 size={17}/></button></div></div><div className="product-card-body"><div className="product-card-top"><span>{category}</span><StockBadge state={state}/></div><h2>{title}</h2><p className="product-ingredient"><b>Principe actif :</b> {product.active_ingredient||'Non renseigné'}</p><p className="product-reference">Réf. {product.reference}</p><div className="product-meta"><span><small>Dosage</small>{product.dosage||'Non renseigné'}</span><span><small>Forme</small>{product.pharmaceutical_form||'Non renseignée'}</span><span><small>Conditionnement</small>{product.packaging||'Non renseigné'}</span><span><small>Laboratoire</small>{product.laboratory||'Non renseigné'}</span></div><p className="product-description">{product.description||'Description non renseignée.'}</p><div className="product-buy"><div className="product-price">{promotion&&<del>{money(Number(product.old_price))} MAD</del>}<strong>{money(Number(product.price))} <small>MAD</small></strong>{promotion&&<span>Économisez {money(Number(product.old_price)-Number(product.price))} MAD</span>}</div><div className="product-buttons"><button className="product-view" onClick={onView}>Voir</button><button className="product-add" disabled={state==='out'} onClick={onAdd}><ShoppingCart size={17}/>{state==='out'?'Indisponible':'Ajouter'}</button></div></div></div></article>}
function StockBadge({state}:{state:'available'|'low'|'out'}){return state==='available'?<Badge tone="green">Disponible</Badge>:state==='low'?<Badge tone="amber">Stock faible</Badge>:<Badge tone="red">Rupture</Badge>}
function ProductDetails({product,category,similar,onClose,onAdd,onSelect}:{product:CatalogProduct;category:string;similar:CatalogProduct[];onClose:()=>void;onAdd:()=>void;onSelect:(p:CatalogProduct)=>void}){const state=stockState(product),title=product.commercial_name||product.name;return <Modal title="Fiche produit" onClose={onClose}><div className="product-detail"><div className="product-gallery"><ProductVisual product={product} category={category}/><div className="gallery-thumbs"><button className="active"><ProductVisual product={product} category={category}/></button></div></div><div className="product-detail-info"><span className="catalog-kicker">{category}</span><h2>{title}</h2><p className="detail-ingredient"><b>Principe actif :</b> {product.active_ingredient||'Non renseigné'}</p><p className="product-reference">Référence {product.reference} · Code-barres {product.barcode||'Non renseigné'}</p><StockBadge state={state}/><dl><div><dt>Dosage</dt><dd>{product.dosage||'Non renseigné'}</dd></div><div><dt>Forme pharmaceutique</dt><dd>{product.pharmaceutical_form||'Non renseignée'}</dd></div><div><dt>Conditionnement</dt><dd>{product.packaging||'Non renseigné'}</dd></div><div><dt>Laboratoire</dt><dd>{product.laboratory||'Non renseigné'}</dd></div><div><dt>Catégorie</dt><dd>{category}</dd></div><div><dt>Disponibilité</dt><dd>{state==='available'?'Disponible':state==='low'?'Stock faible':'Rupture'}</dd></div></dl><p>{product.description||'Aucune description détaillée n’est disponible pour ce produit.'}</p><strong className="detail-price">{money(Number(product.price))} MAD</strong><button className="btn-primary w-full" disabled={state==='out'} onClick={onAdd}><ShoppingCart size={18}/>{state==='out'?'Produit indisponible':'Ajouter au panier'}</button></div></div>{similar.length>0&&<section className="similar-products"><h3>Produits similaires</h3><div>{similar.map(p=><button key={p.id} onClick={()=>onSelect(p)}><ProductVisual product={p} category={category}/><span>{p.commercial_name||p.name}</span></button>)}</div></section>}</Modal>}
