/** Accueil personnalisé de l'espace client, alimenté uniquement par les données réelles. */
import { useQuery } from '@tanstack/react-query'
import { ArrowRight, PackageSearch, ShoppingBag, ShoppingCart, UserRound } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { api } from '../lib/api'
import { useAuth } from '../store/auth'
import type { Category, CustomerOrder, Product } from '../types'
import { Badge, Empty, Loading } from '../components/UI'
export default function ClientHome(){const user=useAuth(s=>s.user),navigate=useNavigate(),products=useQuery({queryKey:['client-products-home'],queryFn:()=>api.get<Product[]>('/products').then(r=>r.data)}),categories=useQuery({queryKey:['client-categories'],queryFn:()=>api.get<Category[]>('/categories').then(r=>r.data)}),orders=useQuery({queryKey:['client-orders'],queryFn:()=>api.get<CustomerOrder[]>('/client/orders').then(r=>r.data)});if(products.isLoading||categories.isLoading||orders.isLoading)return <Loading/>;const recent=[...(products.data||[])].sort((a,b)=>new Date(b.created_at).getTime()-new Date(a.created_at).getTime()).slice(0,4),available=(products.data||[]).filter(p=>p.stock>0).slice(0,4);return <div className="client-home"><section className="client-welcome"><div><span>Espace professionnel</span><h1>Bienvenue {user?.full_name?.split(' ')[0]}</h1><p>Consultez les produits disponibles et préparez facilement votre prochaine commande.</p><div><button className="btn-primary" onClick={()=>navigate('/client/products')}>Consulter le catalogue<ArrowRight size={17}/></button><button className="btn-secondary" onClick={()=>navigate('/client/orders')}>Voir mes commandes</button></div></div><PackageSearch size={110}/></section><Section title="Catégories principales"><div className="home-categories">{categories.data?.slice(0,10).map(c=><button key={c.id} onClick={()=>navigate(`/client/products?category=${c.id}`)}><span>{c.name.charAt(0)}</span><b>{c.name}</b></button>)}</div></Section><Section title="Produits récents"><ProductStrip products={recent} onOpen={id=>navigate(`/client/products/${id}`)}/></Section><Section title="Produits disponibles"><ProductStrip products={available} onOpen={id=>navigate(`/client/products/${id}`)}/></Section><Section title="Dernières commandes">{orders.data?.length?<div className="table-wrap"><table><thead><tr><th>Numéro</th><th>Date</th><th>Montant</th><th>Statut</th></tr></thead><tbody>{orders.data.slice(0,5).map(o=><tr key={o.id} onClick={()=>navigate(`/client/orders/${o.id}`)}><td><b>{o.number}</b></td><td>{new Date(o.created_at).toLocaleDateString('fr-MA')}</td><td>{Number(o.total).toLocaleString('fr-MA')} MAD</td><td><Badge tone={o.status==='rejected'?'red':o.status==='pending'?'amber':'green'}>{o.status}</Badge></td></tr>)}</tbody></table></div>:<Empty text="Vous n’avez encore passé aucune commande."/>}</Section><section className="home-quick"><button onClick={()=>navigate('/client/cart')}><ShoppingCart/>Voir le panier</button><button onClick={()=>navigate('/client/orders')}><ShoppingBag/>Suivre mes commandes</button><button onClick={()=>navigate('/client/profile')}><UserRound/>Modifier mon profil</button></section></div>}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section className="home-section"><h2>{title}</h2>{children}</section>}
function ProductStrip({products,onOpen}:{products:Product[];onOpen:(id:number)=>void}){return products.length?<div className="home-products">{products.map(p=><button key={p.id} onClick={()=>onOpen(p.id)}><div>{p.photo_path?<img src={p.photo_path} alt={p.name}/>:<PackageSearch/>}</div><b>{p.name}</b><span>{Number(p.price).toLocaleString('fr-MA')} MAD</span></button>)}</div>:<Empty text="Aucun produit disponible."/>}
