// Vue synthétique des indicateurs, achats et commandes clients à traiter.
import { useQuery } from '@tanstack/react-query'
import { AlertTriangle, Boxes, Building2, CheckCircle2, Clock3, Eye, PackageCheck, Send, XCircle } from 'lucide-react'
import type { LucideIcon } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { api } from '../lib/api'
import { useAuth } from '../store/auth'
import type { DashboardData, DashboardOrder, Purchase, Supplier } from '../types'
import { Badge, Loading, PageHeader } from '../components/UI'

const statusLabels:Record<string,string>={pending:'En attente',approved:'Approuvée',in_preparation:'En préparation',shipped:'Expédiée',delivered:'Livrée',rejected:'Refusée',cancelled:'Annulée'}
const statusTones:Record<string,'gray'|'blue'|'green'|'red'|'amber'>={pending:'amber',approved:'green',in_preparation:'blue',shipped:'blue',delivered:'green',rejected:'red',cancelled:'gray'}
const nextLabels:Record<string,string>={APPROUVER_OU_REFUSER:'Approuver ou refuser',PREPARER:'Passer en préparation',EXPEDIER:'Marquer comme expédiée'}

export default function Dashboard(){
  const navigate=useNavigate(),role=useAuth(state=>state.user?.role)
  const {data,isLoading}=useQuery({queryKey:['dashboard'],queryFn:()=>api.get<DashboardData>('/dashboard').then(response=>response.data),refetchInterval:30000,refetchOnWindowFocus:true})
  const purchases=useQuery({queryKey:['purchases-dashboard'],refetchInterval:30000,refetchOnWindowFocus:true,queryFn:()=>api.get<Purchase[]>('/purchases').then(response=>response.data)})
  const suppliers=useQuery({queryKey:['suppliers-dashboard'],refetchOnWindowFocus:true,queryFn:()=>api.get<Supplier[]>('/suppliers',{params:{status:'active'}}).then(response=>response.data)})
  if(isLoading||!data)return <Loading/>
  const cards=[['Produits',data.products_count,Boxes,'green'],['Clients',data.clients_count,Building2,'mint'],['Stock total',data.total_stock,PackageCheck,'sage'],['Alertes stock',data.low_stock_count,AlertTriangle,'alert']] as const
  const adminOrderCards=[['Total commandes',data.total_orders,Boxes,'blue'],['Commandes en attente',data.pending_orders,Clock3,'amber'],['Commandes approuvées',data.approved_orders,CheckCircle2,'green'],['Approuvées aujourd’hui',data.approved_today,CheckCircle2,'mint'],['En préparation',data.in_preparation,PackageCheck,'mint'],['Expédiées / livrées',data.shipped_orders+data.delivered_orders,Send,'sage'],['Commandes refusées',data.rejected_orders,XCircle,'alert'],['Montant total validé',`${Number(data.approved_amount).toLocaleString('fr-MA')} MAD`,PackageCheck,'green']] as const
  const purchaseOrderCards=[['Total commandes',data.total_orders,Boxes,'blue'],['Commandes en attente',data.pending_orders,Clock3,'amber'],['Commandes approuvées',data.approved_orders,CheckCircle2,'green'],['Approuvées aujourd’hui',data.approved_today,CheckCircle2,'mint'],['En préparation',data.in_preparation,PackageCheck,'mint'],['Expédiées / livrées',data.shipped_orders+data.delivered_orders,Send,'sage'],['Montant approuvé',`${Number(data.approved_amount).toLocaleString('fr-MA')} MAD`,PackageCheck,'sage']] as const
  const orderCards=role==='admin'?adminOrderCards:purchaseOrderCards
  const chart=data.recent_purchases.map(purchase=>({name:purchase.number,total:Number(purchase.total)})).reverse()
  const allPurchases=purchases.data||[],supplyCards=[['Total achats',data.total_purchases,Boxes,'blue'],['En préparation',data.purchases_in_preparation,Clock3,'gray'],['Commandes envoyées',data.purchases_sent,PackageCheck,'blue'],['Confirmées fournisseur',data.purchases_confirmed,CheckCircle2,'green'],['À réceptionner',data.purchases_confirmed,PackageCheck,'amber'],['Achats réceptionnés',data.purchases_received,CheckCircle2,'green'],['Réceptions du jour',data.receptions_today,CheckCircle2,'mint'],['Fournisseurs actifs',suppliers.data?.length||0,Building2,'sage']] as const
  return <><PageHeader title="Tableau de bord" subtitle={role==='admin'?'Vision globale des activités SOREMED':'Commandes clientes, approvisionnements et stock'}/>
    <div className="dashboard-stats">{cards.map(([label,value,Icon,tone])=><Stat key={label} label={label} value={value} Icon={Icon} tone={tone}/>)}</div>
    <div className="dashboard-order-section"><div className="panel-heading"><div><span>Approvisionnements</span><h3>Achats fournisseurs</h3></div></div><div className="dashboard-stats">{supplyCards.map(([label,value,Icon,tone])=><Stat key={label} label={label} value={value} Icon={Icon} tone={tone}/>)}</div></div>
    <div className="dashboard-order-section"><div className="panel-heading"><div><span>Ventes</span><h3>Commandes clients</h3></div></div><div className={`dashboard-stats ${role==='admin'?'dashboard-stats-six':''}`}>{orderCards.map(([label,value,Icon,tone])=><Stat key={label} label={label} value={value} Icon={Icon} tone={tone}/>)}</div></div>
    <div className="dashboard-grid"><section className="dashboard-panel"><div className="panel-heading"><div><span>Flux entrant</span><h3>Achats fournisseurs récents</h3></div><div className="panel-indicator"><i/>Montants en MAD</div></div><div className="dashboard-chart">{chart.length?<ResponsiveContainer width="100%" height="100%"><BarChart data={chart} margin={{top:10,right:8,left:-12,bottom:0}}><CartesianGrid stroke="#e7efe9" strokeDasharray="4 4" vertical={false}/><XAxis dataKey="name" tick={{fill:'#75857c',fontSize:11}} axisLine={false} tickLine={false}/><YAxis tick={{fill:'#75857c',fontSize:11}} axisLine={false} tickLine={false}/><Tooltip/><Bar dataKey="total" fill="#188a57" radius={[8,8,2,2]} maxBarSize={48}/></BarChart></ResponsiveContainer>:<div className="chart-empty">Aucun achat fournisseur</div>}</div><div className="recent-list">{allPurchases.slice(0,4).map(purchase=><div className="recent-item" key={purchase.id}><div className="recent-icon"><PackageCheck size={17}/></div><div><strong>{purchase.number}</strong><span>{purchase.supplier?.name||'Fournisseur'}</span></div><b>{Number(purchase.total).toLocaleString('fr-MA')} <small>MAD</small></b></div>)}</div></section>
      <section className="dashboard-panel"><div className="panel-heading"><div><span>Flux sortant</span><h3>Commandes clients à traiter</h3></div><div className="panel-indicator"><i/>Actualisation automatique</div></div>{data.orders_to_process.length?<div className="dashboard-orders-list">{data.orders_to_process.slice(0,8).map(order=><OrderRow key={order.id} order={order} onView={()=>navigate(`/customer-orders/${order.id}`)}/>)}</div>:<div className="chart-empty">Aucune commande à traiter</div>}{role==='admin'&&data.recent_orders.length>0&&<div className="dashboard-recent-orders"><div className="panel-heading"><div><span>Activité globale</span><h3>Commandes récentes</h3></div></div>{data.recent_orders.slice(0,4).map(order=><OrderRow key={`recent-${order.id}`} order={order} onView={()=>navigate(`/customer-orders/${order.id}`)} compact/>)}</div>}</section></div>
  </>
}

function OrderRow({order,onView,compact=false}:{order:DashboardOrder;onView:()=>void;compact?:boolean}){return <div className={`dashboard-order-row ${compact?'compact':''}`}><div className="recent-icon"><Clock3 size={17}/></div><div className="dashboard-order-identity"><strong>{order.order_number}</strong><span>{order.client_name} · {new Date(order.created_at).toLocaleDateString('fr-MA')}</span>{!compact&&order.next_action&&<small>{nextLabels[order.next_action]||order.next_action}</small>}</div><div className="dashboard-order-status"><b>{Number(order.total_amount).toLocaleString('fr-MA')} <small>MAD</small></b><Badge tone={statusTones[order.status]||'gray'}>{statusLabels[order.status]||order.status}</Badge></div><button className="dashboard-order-view" onClick={onView} aria-label={`Voir ${order.order_number}`}><Eye size={17}/><span>Voir</span></button></div>}
function Stat({label,value,Icon,tone}:{label:string;value:string|number;Icon:LucideIcon;tone:string}){return <div className={`stat-card stat-${tone}`}><div className="stat-card-top"><span>{label}</span><div><Icon size={22}/></div></div><strong>{value}</strong><small>Données actualisées</small><span className="stat-decoration"/></div>}
