// Inventaire et alertes : lecture professionnelle du stock, sans mutation directe.
import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { useLocation, useNavigate } from 'react-router-dom'
import { AlertTriangle, Boxes, PackageX, Search, Warehouse } from 'lucide-react'
import { api } from '../lib/api'
import type { Product, StockMovement } from '../types'
import { Badge, Empty, Loading, PageHeader } from '../components/UI'

export default function Inventory(){
 const location=useLocation(),navigate=useNavigate(),alerts=location.pathname.endsWith('/alerts'),[q,setQ]=useState('')
 const products=useQuery({queryKey:['inventory-products'],queryFn:()=>api.get<Product[]>('/products').then(response=>response.data)}),movements=useQuery({queryKey:['inventory-last-movements'],queryFn:()=>api.get<StockMovement[]>('/stock/movements').then(response=>response.data)})
 const latest=new Map<number,StockMovement>();for(const movement of movements.data||[])if(!latest.has(movement.product_id))latest.set(movement.product_id,movement)
 const rows=(products.data||[]).filter(product=>(!alerts||product.stock<=product.minimum_stock)&&`${product.name} ${product.reference} ${product.active_ingredient||''}`.toLowerCase().includes(q.toLowerCase()))
 const total=(products.data||[]).reduce((sum,product)=>sum+product.stock*Number(product.price),0),out=(products.data||[]).filter(product=>product.stock===0).length,low=(products.data||[]).filter(product=>product.stock>0&&product.stock<=product.minimum_stock).length
 return <><PageHeader title={alerts?'Alertes stock':'Inventaire'} subtitle={alerts?'Produits en rupture ou sous leur seuil minimum':'Vision valorisée des quantités disponibles, sans modification directe'} action={<button className="btn-secondary" onClick={()=>navigate('/stock/movements')}>Voir les mouvements</button>}/><div className="erp-kpi-grid"><Kpi icon={Boxes} label="Produits suivis" value={(products.data||[]).length}/><Kpi icon={PackageX} label="Ruptures" value={out}/><Kpi icon={AlertTriangle} label="Stock faible" value={low}/><Kpi icon={Warehouse} label="Valeur indicative" value={`${total.toLocaleString('fr-MA')} MAD`}/></div><div className="erp-toolbar"><div className="relative"><Search className="absolute left-3 top-3 text-slate-400" size={18}/><input className="input pl-10" value={q} onChange={event=>setQ(event.target.value)} placeholder="Produit, référence ou principe actif…"/></div></div>{products.isLoading||movements.isLoading?<Loading/>:<div className="table-wrap">{rows.length?<table><thead><tr><th>Produit</th><th>Référence</th><th>Stock actuel</th><th>Stock minimum</th><th>Valeur du stock</th><th>Dernier mouvement</th><th>Statut</th><th>Historique</th></tr></thead><tbody>{rows.map(product=>{const movement=latest.get(product.id),state=product.stock===0?['Rupture','red'] as const:product.stock<=product.minimum_stock?['Stock faible','amber'] as const:['Disponible','green'] as const;return <tr key={product.id}><td><div className="inventory-product">{product.photo_path?<img src={product.photo_path} alt="" loading="lazy"/>:<span>{product.name.charAt(0)}</span>}<div><b>{product.commercial_name||product.name}</b><small>{product.active_ingredient||'Principe actif non renseigné'}</small></div></div></td><td className="font-mono text-xs">{product.reference}</td><td className="font-bold">{product.stock}</td><td>{product.minimum_stock}</td><td>{(product.stock*Number(product.price)).toLocaleString('fr-MA')} MAD</td><td>{movement?new Date(movement.created_at).toLocaleString('fr-MA'):'—'}</td><td><Badge tone={state[1]}>{state[0]}</Badge></td><td><button className="btn-secondary" onClick={()=>navigate(`/stock/movements?product_id=${product.id}`)}>Consulter</button></td></tr>})}</tbody></table>:<Empty text={alerts?'Aucune alerte de stock.':'Aucun produit dans l’inventaire.'}/>}</div>}</>
}
function Kpi({icon:Icon,label,value}:{icon:any;label:string;value:string|number}){return <div className="erp-kpi"><Icon/><div><span>{label}</span><strong>{value}</strong></div></div>}
