// Vue de suivi détaillée d'une commande client pour les équipes Admin et Achats.
import { useMemo, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { ArrowLeft, CheckCircle2, Clock3, MapPin, PackageCheck, Printer, Truck, UserRound, XCircle } from 'lucide-react'
import { useNavigate, useParams } from 'react-router-dom'
import { api } from '../lib/api'
import type { CustomerOrder, OrderStatus, Product } from '../types'
import { Badge, Empty, Loading, Modal, Notice } from '../components/UI'

const labels:Record<OrderStatus,string>={draft:'Brouillon',pending:'En attente',approved:'Approuvée',rejected:'Refusée',in_preparation:'En préparation',shipped:'Expédiée',delivered:'Livrée',cancelled:'Annulée',confirmed:'Confirmée',prepared:'Préparée'}
const tones:Record<OrderStatus,'gray'|'blue'|'green'|'red'|'amber'>={draft:'gray',pending:'amber',approved:'green',rejected:'red',in_preparation:'blue',shipped:'blue',delivered:'green',cancelled:'red',confirmed:'green',prepared:'blue'}
const money=(value:number)=>`${Number(value).toLocaleString('fr-MA',{minimumFractionDigits:2,maximumFractionDigits:2})} MAD`
const dateTime=(value?:string)=>value?new Date(value).toLocaleString('fr-MA',{dateStyle:'medium',timeStyle:'short'}):'—'
const message=(error:any)=>typeof error.response?.data?.detail==='string'?error.response.data.detail:'Une erreur est survenue.'

export default function OrderDetail(){
 const {id}=useParams(),navigate=useNavigate(),qc=useQueryClient();const [dialog,setDialog]=useState<'approve'|'reject'|'progress'|null>(null),[reason,setReason]=useState(''),[comment,setComment]=useState(''),[notice,setNotice]=useState<{message:string;type:'success'|'error'}|null>(null)
 const orderQuery=useQuery({queryKey:['order',id],enabled:!!id,queryFn:()=>api.get<CustomerOrder>(`/orders/${id}`).then(r=>r.data)}),productsQuery=useQuery({queryKey:['products','order-detail'],queryFn:()=>api.get<Product[]>('/products').then(r=>r.data)})
 const products=useMemo(()=>new Map((productsQuery.data||[]).map(product=>[product.id,product])),[productsQuery.data]),order=orderQuery.data
 const nextStatus:Partial<Record<OrderStatus,OrderStatus>>={approved:'in_preparation',in_preparation:'shipped',shipped:'delivered',confirmed:'in_preparation',prepared:'shipped'},next=order?nextStatus[order.status]:undefined
 const action=useMutation({mutationFn:async()=>{if(!order)return;if(dialog==='approve')return api.patch(`/orders/${order.id}/approve`,{comment:comment.trim()||null});if(dialog==='reject')return api.patch(`/orders/${order.id}/reject`,{reason:reason.trim(),comment:comment.trim()||null});if(dialog==='progress'&&next)return api.patch(`/orders/${order.id}/status`,null,{params:{status:next}})},onSuccess:()=>{qc.invalidateQueries({queryKey:['order',id]});qc.invalidateQueries({queryKey:['orders']});qc.invalidateQueries({queryKey:['dashboard']});setDialog(null);setReason('');setComment('');setNotice({message:'La commande a été mise à jour.',type:'success'})},onError:error=>setNotice({message:message(error),type:'error'})})
 if(orderQuery.isLoading)return <Loading/>;if(orderQuery.isError||!order)return <div className="order-detail-empty"><Empty text="Cette commande est introuvable ou inaccessible."/><button className="btn-secondary" onClick={()=>navigate('/customer-orders')}>Retour aux commandes</button></div>
 const client=order.client,history=[{label:'Commande créée',date:order.created_at,detail:'Demande enregistrée par le client'},...(order.approved_at?[{label:'Commande approuvée',date:order.approved_at,detail:order.approved_by?`Par l’utilisateur #${order.approved_by}`:'Validation du service achats'}]:[]),...(order.rejected_at?[{label:'Commande refusée',date:order.rejected_at,detail:order.rejection_reason||'Demande refusée'}]:[]),...(order.updated_at!==order.created_at&&!order.approved_at&&!order.rejected_at?[{label:'Dernière mise à jour',date:order.updated_at,detail:`Statut : ${labels[order.status]}`}]:[])]
 return <div className="order-detail-page"><header className="order-detail-header"><button className="order-back" onClick={()=>navigate('/customer-orders')}><ArrowLeft size={18}/>Commandes clients</button><div className="order-title-row"><div><span className="page-eyebrow">Suivi de commande</span><h2>{order.number}</h2><p>Créée le {dateTime(order.created_at)}</p></div><Badge tone={tones[order.status]}>{labels[order.status]}</Badge></div><div className="order-detail-actions no-print"><button className="btn-secondary" onClick={()=>window.print()}><Printer size={17}/>Imprimer</button>{order.status==='pending'&&<><button className="order-reject" onClick={()=>setDialog('reject')}><XCircle size={17}/>Refuser</button><button className="btn-primary" onClick={()=>setDialog('approve')}><CheckCircle2 size={17}/>Approuver</button></>}{next&&<button className="btn-primary" onClick={()=>setDialog('progress')}><PackageCheck size={17}/>{next==='in_preparation'?'Mettre en préparation':next==='shipped'?'Marquer expédiée':'Marquer livrée'}</button>}</div></header>
 <div className="order-detail-grid"><main className="order-detail-main"><section className="order-card"><div className="order-section-heading"><UserRound/><div><h3>Informations client</h3><p>Coordonnées de facturation et de livraison</p></div></div><dl className="customer-compact"><div><dt>Nom</dt><dd>{client?.name||`Client #${order.client_id}`}</dd></div><div><dt>Société</dt><dd>{client?.company_name||'—'}</dd></div><div><dt>Email</dt><dd>{client?.email||'—'}</dd></div><div><dt>Téléphone</dt><dd>{client?.phone||'—'}</dd></div><div className="customer-address"><dt>Adresse</dt><dd><MapPin size={15}/>{[client?.address,client?.city].filter(Boolean).join(', ')||'—'}</dd></div></dl></section>
 <section className="order-card"><div className="order-section-heading"><PackageCheck/><div><h3>Produits commandés</h3><p>{order.lines.reduce((sum,line)=>sum+line.quantity,0)} article(s)</p></div></div><div className="order-products"><table><thead><tr><th>Référence</th><th>Produit</th><th>Principe actif</th><th>Dosage</th><th>Forme</th><th>Qté</th><th>Prix unitaire</th><th>Sous-total</th></tr></thead><tbody>{order.lines.map(line=>{const product=products.get(line.product_id);return <tr key={line.id}><td className="font-mono text-xs">{line.product_reference}</td><td><strong>{line.product_name}</strong><small>{product?.packaging||''}</small></td><td>{product?.active_ingredient||'—'}</td><td>{product?.dosage||'—'}</td><td>{product?.pharmaceutical_form||'—'}</td><td><b>{line.quantity}</b></td><td>{money(line.unit_price)}</td><td><strong>{money(line.line_total)}</strong></td></tr>})}</tbody></table></div></section>
 <section className="order-card"><div className="order-section-heading"><Clock3/><div><h3>Historique</h3><p>Événements disponibles pour cette commande</p></div></div><div className="order-timeline">{history.map((item,index)=><div key={`${item.label}-${item.date}`} className="timeline-item"><i className={index===history.length-1?'active':''}/><div><b>{item.label}</b><span>{item.detail}</span></div><time>{dateTime(item.date)}</time></div>)}</div></section></main>
 <aside className="order-detail-aside"><section className="order-card order-summary"><h3>Résumé financier</h3><div><span>Sous-total</span><b>{money(order.total)}</b></div><div><span>Remise</span><b>0,00 MAD</b></div><div><span>TVA additionnelle</span><b>0,00 MAD</b></div><div className="order-grand-total"><span>Total général</span><strong>{money(order.total)}</strong></div></section><section className="order-card"><h3>Suivi logistique</h3><div className="workflow-mini"><div className="done"><CheckCircle2/>Reçue</div><div className={['approved','in_preparation','shipped','delivered','confirmed','prepared'].includes(order.status)?'done':''}><CheckCircle2/>Approuvée</div><div className={['in_preparation','shipped','delivered','prepared'].includes(order.status)?'done':''}><PackageCheck/>Préparation</div><div className={['shipped','delivered'].includes(order.status)?'done':''}><Truck/>Expédition</div><div className={order.status==='delivered'?'done':''}><CheckCircle2/>Livraison</div></div></section><section className="order-card order-comments"><h3>Commentaires</h3><div><span>Message du client</span><p>Aucun commentaire client enregistré.</p></div><div><span>Service achats</span><p>{order.purchase_comment||'Aucun commentaire interne.'}</p></div>{order.rejection_reason&&<div className="rejection-note"><span>Motif du refus</span><p>{order.rejection_reason}</p></div>}</section></aside></div>
 {dialog&&<Modal title={dialog==='approve'?'Approuver la commande':dialog==='reject'?'Refuser la commande':'Faire avancer la commande'} onClose={()=>setDialog(null)}><div className="space-y-4"><p className="text-sm text-slate-600">Commande <b>{order.number}</b> · {money(order.total)}</p>{dialog==='reject'&&<label><span className="label">Motif du refus *</span><textarea className="input" value={reason} onChange={event=>setReason(event.target.value)} placeholder="Indiquez clairement le motif"/></label>}{dialog!=='progress'&&<label><span className="label">Commentaire du service achats</span><textarea className="input" value={comment} onChange={event=>setComment(event.target.value)} placeholder="Commentaire visible par le client"/></label>}{dialog==='progress'&&<p className="rounded-xl bg-emerald-50 p-4 text-sm text-emerald-800">Le statut passera à <b>{next&&labels[next]}</b>.</p>}<div className="flex justify-end gap-3"><button className="btn-secondary" onClick={()=>setDialog(null)}>Annuler</button><button className="btn-primary" disabled={action.isPending||(dialog==='reject'&&reason.trim().length<2)} onClick={()=>action.mutate()}>{action.isPending?'Traitement…':'Confirmer'}</button></div></div></Modal>}{notice&&<Notice {...notice} onClose={()=>setNotice(null)}/>}</div>
}
