// Centre opérationnel des réceptions fournisseurs, adossé au workflow d'achat existant.
import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { CalendarClock, CheckCircle2, PackageCheck, Search, Truck } from 'lucide-react'
import { api } from '../lib/api'
import type { Purchase } from '../types'
import { Badge, Confirm, Empty, Loading, Notice, PageHeader } from '../components/UI'
import { PURCHASE_STATUS_LABELS, PURCHASE_STATUS_TONES, purchaseStatus } from '../constants/purchaseStatus'

export default function Receipts(){
 const qc=useQueryClient(),[q,setQ]=useState(''),[selected,setSelected]=useState<Purchase|null>(null),[notice,setNotice]=useState<{message:string;type:'success'|'error'}|null>(null)
 const query=useQuery({queryKey:['supplier-receipts'],queryFn:()=>api.get<Purchase[]>('/purchases').then(response=>response.data),refetchOnWindowFocus:true})
 const receive=useMutation({mutationFn:()=>api.patch(`/purchases/${selected!.id}/receive`),onSuccess:()=>{qc.invalidateQueries();setSelected(null);setNotice({message:'Réception validée. Le stock a été mis à jour automatiquement.',type:'success'})},onError:(error:any)=>setNotice({message:error.response?.data?.detail||'La réception n’a pas pu être validée.',type:'error'})})
 const rows=(query.data||[]).filter(purchase=>['CONFIRMEE_PAR_FOURNISSEUR','RECEPTIONNEE'].includes(purchase.status)&&`${purchase.number} ${purchase.supplier?.name||''}`.toLowerCase().includes(q.toLowerCase()))
 const pending=rows.filter(purchase=>purchase.status==='CONFIRMEE_PAR_FOURNISSEUR'),received=rows.filter(purchase=>purchase.status==='RECEPTIONNEE')
 return <><PageHeader title="Réceptions fournisseurs" subtitle="Contrôle des livraisons et mise à jour automatique du stock"/><div className="erp-kpi-grid"><Kpi icon={Truck} label="À réceptionner" value={pending.length}/><Kpi icon={CheckCircle2} label="Réceptions réalisées" value={received.length}/><Kpi icon={CalendarClock} label="En retard" value={pending.filter(purchase=>purchase.supplier_confirmed_delivery_date&&new Date(purchase.supplier_confirmed_delivery_date)<new Date()).length}/></div><div className="erp-toolbar"><div className="relative"><Search className="absolute left-3 top-3 text-slate-400" size={18}/><input className="input pl-10" value={q} onChange={event=>setQ(event.target.value)} placeholder="Commande ou fournisseur…"/></div></div>{query.isLoading?<Loading/>:<div className="table-wrap">{rows.length?<table><thead><tr><th>Commande</th><th>Fournisseur</th><th>Livraison confirmée</th><th>Lignes</th><th>Quantité commandée</th><th>Quantité reçue</th><th>Écart</th><th>Statut</th><th>Validation</th></tr></thead><tbody>{rows.map(purchase=>{const ordered=purchase.lines.reduce((sum,line)=>sum+line.quantity,0),done=purchase.lines.reduce((sum,line)=>sum+line.received_quantity,0);return <tr key={purchase.id}><td><b>{purchase.number}</b></td><td>{purchase.supplier?.name||'—'}</td><td>{purchase.supplier_confirmed_delivery_date?new Date(purchase.supplier_confirmed_delivery_date).toLocaleDateString('fr-MA'):'—'}</td><td>{purchase.lines.length}</td><td>{ordered}</td><td>{done}</td><td className={ordered-done?'text-amber-700':'text-emerald-700'}>{ordered-done}</td><td><Badge tone={PURCHASE_STATUS_TONES[purchaseStatus(purchase.status)]}>{PURCHASE_STATUS_LABELS[purchaseStatus(purchase.status)]}</Badge></td><td>{purchase.status!=='received'?<button className="btn-primary" onClick={()=>setSelected(purchase)}><PackageCheck size={16}/>Valider la réception</button>:<span className="text-sm font-semibold text-emerald-700">Réceptionnée</span>}</td></tr>})}</tbody></table>:<Empty text="Aucune réception fournisseur à afficher."/>}</div>}{selected&&<Confirm title={`Réceptionner ${selected.number} ?`} message="Les quantités commandées seront ajoutées au stock et un mouvement traçable sera créé pour chaque produit." onCancel={()=>setSelected(null)} onConfirm={()=>receive.mutate()} busy={receive.isPending}/>} {notice&&<Notice {...notice} onClose={()=>setNotice(null)}/>}</>
}
function Kpi({icon:Icon,label,value}:{icon:any;label:string;value:number}){return <div className="erp-kpi"><Icon/><div><span>{label}</span><strong>{value}</strong></div></div>}
