// CRUD complet des utilisateurs, clients et produits.
import { useEffect, useRef, useState, type FormEvent } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { CheckCircle2, Edit3, FileSpreadsheet, Plus, Power, Search, Trash2, XCircle } from 'lucide-react'
import { api } from '../lib/api'
import type { Category, Client, Product, User } from '../types'
import { Badge, Confirm, Empty, Loading, Modal, Notice, PageHeader } from '../components/UI'
import { useAuth } from '../store/auth'
import { SimpleModal } from '../components/SimpleModal'
type Kind='clients'|'products'|'users'; type Row=Client|Product|User
interface ImportResult {created:number;updated:number;ignored:number;errors:{row:number;message:string}[]}
const config={clients:{title:'Clients',subtitle:'Répertoire commercial et coordonnées'},products:{title:'Produits',subtitle:'Catalogue, catégories, prix et niveaux de stock'},users:{title:'Utilisateurs',subtitle:'Comptes, rôles et accès à la plateforme'}}
const errorText=(e:any)=>typeof e.response?.data?.detail==='string'?e.response.data.detail:'Une erreur est survenue'

export default function Resources({kind}:{kind:Kind}) {
  const importInput=useRef<HTMLInputElement>(null)
  const qc=useQueryClient(),[q,setQ]=useState(''),[status,setStatus]=useState(''),[categoryFilter,setCategoryFilter]=useState(''),[page,setPage]=useState(1),[editing,setEditing]=useState<Row|null>(null),[open,setOpen]=useState(false),[showAddProduct,setShowAddProduct]=useState(false),[showExcelImport,setShowExcelImport]=useState(false),[importFile,setImportFile]=useState<File|null>(null),[importResult,setImportResult]=useState<ImportResult|null>(null),[productModalError,setProductModalError]=useState(''),[importModalError,setImportModalError]=useState(''),[deleting,setDeleting]=useState<Row|null>(null),[rejecting,setRejecting]=useState<User|null>(null),[notice,setNotice]=useState<{message:string;type:'success'|'error'}|null>(null)
  const role=useAuth(s=>s.user?.role),canEdit=role==='admin'||(kind==='products'&&role==='achats')||(kind==='clients'&&role==='client')
  const categories=useQuery({queryKey:['categories'],queryFn:()=>api.get<Category[]>('/categories').then(r=>r.data),enabled:kind==='products'})
  const query=useQuery({queryKey:[kind,q,status,categoryFilter],queryFn:()=>api.get<Row[]>(`/${kind}`,{params:{q,status:kind!=='users'&&status||undefined,category_id:kind==='products'&&categoryFilter||undefined,active:kind==='users'&&(status==='active'||status==='inactive')?status==='active':undefined,approval_status:kind==='users'&&(status==='pending'||status==='rejected')?status:undefined}}).then(r=>r.data)})
  const save=useMutation({mutationFn:async({body,photo}:{body:any;photo?:File})=>{const endpoint=editing?`/${kind}/${editing.id}`:`/${kind}`;const response=await api.request({url:endpoint,method:editing?'PUT':'POST',data:body});if(kind==='products'&&photo){const form=new FormData();form.append('photo',photo);await api.post(`/products/${response.data.id}/photo`,form)}},onSuccess:()=>{qc.invalidateQueries({queryKey:[kind]});setOpen(false);setShowAddProduct(false);setProductModalError('');setEditing(null);setNotice({message:'Enregistrement effectué avec succès',type:'success'})},onError:e=>{const message=errorText(e);if(kind==='products'&&!editing)setProductModalError(message);else setNotice({message,type:'error'})}})
  const remove=useMutation({mutationFn:(row:Row)=>api.delete(`/${kind}/${row.id}`),onSuccess:()=>{qc.invalidateQueries({queryKey:[kind]});setDeleting(null);setNotice({message:'Élément supprimé',type:'success'})},onError:e=>setNotice({message:errorText(e),type:'error'})})
  const toggle=useMutation({mutationFn:(row:Row)=>api.patch(`/${kind}/${row.id}/status`),onSuccess:()=>{qc.invalidateQueries({queryKey:[kind]});setNotice({message:'Statut mis à jour',type:'success'})},onError:e=>setNotice({message:errorText(e),type:'error'})})
  const approval=useMutation({mutationFn:({user,action}:{user:User;action:'approve'|'reject'|'deactivate'})=>api.patch(`/users/${user.id}/${action}`),onSuccess:(_,variables)=>{qc.invalidateQueries({queryKey:['users']});setRejecting(null);setNotice({message:variables.action==='approve'?'Compte approuvé':variables.action==='reject'?'Demande refusée':'Compte désactivé',type:'success'})},onError:e=>setNotice({message:errorText(e),type:'error'})})
  const importer=useMutation({mutationFn:async()=>{if(!importFile?.name.toLowerCase().endsWith('.xlsx'))throw new Error('Sélectionnez un fichier .xlsx valide');const form=new FormData();form.append('file',importFile);return api.post<ImportResult>('/products/import',form)},onSuccess:response=>{setImportResult(response.data);setImportModalError('');qc.invalidateQueries({queryKey:['products']});qc.invalidateQueries({queryKey:['categories']});const r=response.data;setNotice({message:`Import terminé. ${r.created} produit(s) ajouté(s), ${r.updated} mis à jour.`,type:r.errors.length?'error':'success'})},onError:e=>setImportModalError(e instanceof Error&&!('response' in e)?e.message:errorText(e))})
  const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const fd=new FormData(e.currentTarget),photo=fd.get('photo') as File;fd.delete('photo');const body=Object.fromEntries(fd.entries()) as any;if(kind==='products'){body.name=body.commercial_name||body.name;body.price=Number(body.price);body.default_purchase_price=body.default_purchase_price===''?null:Number(body.default_purchase_price);body.stock=Number(body.stock||0);body.minimum_stock=Number(body.minimum_stock);body.category_id=body.category_id?Number(body.category_id):null;body.barcode=body.barcode||null;body.photo_path=body.photo_path||(editing as Product)?.photo_path||null}if(kind==='users'&&editing&&!body.password)delete body.password;save.mutate({body,photo:photo?.size?photo:undefined})}
  const startEdit=(row:Row)=>{setEditing(row);setOpen(true)}
  const pageSize=20,totalPages=Math.max(1,Math.ceil((query.data?.length||0)/pageSize)),visibleRows=kind==='products'?(query.data||[]).slice((page-1)*pageSize,page*pageSize):(query.data||[])
  return <><PageHeader title={config[kind].title} subtitle={config[kind].subtitle} action={canEdit?<div className="flex gap-2">{kind==='products'&&<button type="button" className="btn-secondary" onClick={()=>{setShowAddProduct(false);setImportFile(null);setImportResult(null);setImportModalError('');setShowExcelImport(true)}}><FileSpreadsheet size={18}/>Importer Excel</button>}<button type="button" className="btn-primary" onClick={()=>{setEditing(null);if(kind==='products'){setShowExcelImport(false);setProductModalError('');setShowAddProduct(true)}else setOpen(true)}}><Plus size={18}/>Ajouter</button></div>:undefined}/>
    <div className="mb-4 flex flex-col gap-3 sm:flex-row"><div className="relative max-w-md flex-1"><Search className="absolute left-3 top-3 text-slate-400" size={18}/><input className="input pl-10" placeholder={kind==='products'?'Rechercher par nom ou référence…':'Rechercher…'} value={q} onChange={e=>{setQ(e.target.value);setPage(1)}}/></div>{kind==='products'&&<select className="input sm:w-52" value={categoryFilter} onChange={e=>{setCategoryFilter(e.target.value);setPage(1)}}><option value="">Toutes les catégories</option>{categories.data?.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select>}<select className="input sm:w-48" value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="">Tous les statuts</option>{kind==='users'&&<option value="pending">En attente</option>}{kind==='users'&&<option value="rejected">Refusés</option>}<option value="active">Actifs</option><option value="inactive">Inactifs</option></select></div>
    {query.isLoading?<Loading/>:<><div className="table-wrap">{visibleRows.length?<ResourceTable kind={kind} rows={visibleRows} categories={categories.data||[]} canEdit={canEdit} onEdit={startEdit} onDelete={setDeleting} onToggle={row=>toggle.mutate(row)} onApprove={user=>approval.mutate({user,action:'approve'})} onReject={setRejecting} onDeactivate={user=>approval.mutate({user,action:'deactivate'})}/>:<Empty/>}</div>{kind==='products'&&totalPages>1&&<div className="mt-4 flex items-center justify-end gap-3 text-sm"><button className="btn-secondary py-2" disabled={page===1} onClick={()=>setPage(p=>p-1)}>Précédent</button><span>Page {page} sur {totalPages}</span><button className="btn-secondary py-2" disabled={page===totalPages} onClick={()=>setPage(p=>p+1)}>Suivant</button></div>}</>}
    {open&&<Modal title={`${editing?'Modifier':'Ajouter'} — ${config[kind].title}`} onClose={()=>{setOpen(false);setEditing(null)}}><form onSubmit={submit} className="grid gap-4 sm:grid-cols-2"><ResourceForm kind={kind} row={editing} categories={categories.data||[]} onCategoryAdded={()=>qc.invalidateQueries({queryKey:['categories']})}/><div className="flex justify-end gap-3 pt-2 sm:col-span-2"><button type="button" className="btn-secondary" onClick={()=>setOpen(false)}>Annuler</button><button className="btn-primary" disabled={save.isPending}>{save.isPending?'Enregistrement…':'Enregistrer'}</button></div></form></Modal>}
    <SimpleModal open={kind==='products'&&showAddProduct} title="Ajouter un produit" onClose={()=>setShowAddProduct(false)}><form onSubmit={submit} className="grid gap-4 sm:grid-cols-2">{productModalError&&<div className="sm:col-span-2 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{productModalError}</div>}<ResourceForm kind="products" row={null} categories={categories.data||[]} onCategoryAdded={()=>qc.invalidateQueries({queryKey:['categories']})}/><div className="flex justify-end gap-3 pt-2 sm:col-span-2"><button type="button" className="btn-secondary" onClick={()=>setShowAddProduct(false)}>Annuler</button><button type="submit" className="btn-primary" disabled={save.isPending}>{save.isPending?'Enregistrement…':'Enregistrer'}</button></div></form></SimpleModal>
    <SimpleModal open={kind==='products'&&showExcelImport} title="Importer des produits depuis Excel" onClose={()=>setShowExcelImport(false)}><form className="space-y-4" onSubmit={event=>{event.preventDefault();importer.mutate()}}><div className="rounded-lg bg-blue-50 p-3 text-xs text-blue-700">Fichier .xlsx uniquement, 10 Mo maximum. L’ancien format et le format enrichi sont acceptés.</div>{importModalError&&<div className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{importModalError}</div>}<input ref={importInput} className="sr-only" type="file" accept=".xlsx" onChange={e=>{const file=e.target.files?.[0]||null;setImportFile(file);setImportResult(null);setImportModalError(file&&!file.name.toLowerCase().endsWith('.xlsx')?'Seuls les fichiers .xlsx sont acceptés.':'')}}/><button type="button" className="btn-secondary" onClick={()=>importInput.current?.click()}><FileSpreadsheet size={17}/>Choisir un fichier</button>{importFile&&<div className="flex items-center gap-2 rounded-lg border border-slate-200 p-3 text-sm"><FileSpreadsheet className="text-emerald-600" size={20}/><span className="font-medium">{importFile.name}</span><span className="ml-auto text-xs text-slate-500">{(importFile.size/1024).toFixed(1)} Ko</span></div>}{importResult&&<div className="rounded-lg bg-slate-50 p-4 text-sm"><b>Rapport d’import</b><p className="mt-2">{importResult.created} créé(s) · {importResult.updated} mis à jour · {importResult.ignored} ignoré(s)</p>{importResult.errors.length>0&&<div className="mt-3 max-h-36 overflow-y-auto text-xs text-red-700">{importResult.errors.map(error=><div key={`${error.row}-${error.message}`}>Ligne {error.row} : {error.message}</div>)}</div>}</div>}<div className="flex flex-wrap justify-end gap-3"><button type="button" className="btn-secondary" onClick={async()=>{const response=await api.get('/products/import-template',{responseType:'blob'}),url=URL.createObjectURL(response.data),link=document.createElement('a');link.href=url;link.download='modele-import-produits.xlsx';link.click();URL.revokeObjectURL(url)}}>Télécharger le modèle</button><button type="button" className="btn-secondary" onClick={()=>setShowExcelImport(false)}>Annuler</button><button type="submit" className="btn-primary" disabled={!importFile||!!importModalError||importer.isPending}>{importer.isPending?'Import en cours…':'Importer'}</button></div></form></SimpleModal>
    {deleting&&<Confirm title="Confirmer la suppression" message="Cette opération est définitive. Voulez-vous continuer ?" onCancel={()=>setDeleting(null)} onConfirm={()=>remove.mutate(deleting)} busy={remove.isPending}/>} {rejecting&&<Confirm title="Refuser cette demande ?" message="Le compte et la fiche client seront conservés avec le statut Refusé. Le client ne pourra pas se connecter." onCancel={()=>setRejecting(null)} onConfirm={()=>approval.mutate({user:rejecting,action:'reject'})} busy={approval.isPending}/>} {notice&&<Notice {...notice} onClose={()=>setNotice(null)}/>}</>
}

function Field({label,name,type='text',required=false,value,span=false}:{label:string;name:string;type?:string;required?:boolean;value?:string|number|null;span?:boolean}) { return <label className={span?'sm:col-span-2':''}><span className="label">{label}</span><input className="input" name={name} type={type} required={required} defaultValue={value??''}/></label> }
function ResourceForm({kind,row,categories,onCategoryAdded}:{kind:Kind;row:Row|null;categories:Category[];onCategoryAdded:()=>void}) {
  const [categoryName,setCategoryName]=useState(''),[catError,setCatError]=useState('');useEffect(()=>setCatError(''),[kind])
  const addCategory=async()=>{if(categoryName.trim().length<2)return;try{await api.post('/categories',{name:categoryName});setCategoryName('');onCategoryAdded()}catch(e){setCatError(errorText(e))}}
  if(kind==='clients'){const x=row as Client|null;return <><Field label="Nom" name="name" required value={x?.name}/><Field label="Raison sociale" name="company_name" value={x?.company_name}/><Field label="ICE" name="ice" value={x?.ice}/><Field label="RC" name="rc" value={x?.rc}/><Field label="Adresse" name="address" value={x?.address} span/><Field label="Ville" name="city" value={x?.city}/><Field label="Téléphone" name="phone" value={x?.phone}/><Field label="Email" name="email" type="email" value={x?.email}/><label><span className="label">Statut</span><select className="input" name="status" defaultValue={x?.status||'active'}><option value="active">Actif</option><option value="inactive">Inactif</option></select></label></>}
  if(kind==='products'){const x=row as Product|null;return <><Field label="Référence" name="reference" required value={x?.reference}/><Field label="Nom commercial" name="commercial_name" required value={x?.commercial_name||x?.name}/><Field label="Principe actif" name="active_ingredient" value={x?.active_ingredient}/><Field label="Prix de vente (MAD)" name="price" type="number" required value={x?.price||0}/><Field label="Prix d’achat par défaut (MAD)" name="default_purchase_price" type="number" value={x?.default_purchase_price}/><Field label="Dosage" name="dosage" value={x?.dosage}/><Field label="Forme pharmaceutique" name="pharmaceutical_form" value={x?.pharmaceutical_form}/><Field label="Conditionnement" name="packaging" value={x?.packaging}/><Field label="Laboratoire" name="laboratory" value={x?.laboratory}/><Field label="Code-barres" name="barcode" value={x?.barcode}/><Field label="Seuil minimum" name="minimum_stock" type="number" value={x?.minimum_stock||0}/><label><span className="label">Catégorie</span><select className="input" name="category_id" defaultValue={x?.category_id||''} required><option value="">Sélectionner</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label><span className="label">Statut</span><select className="input" name="status" defaultValue={x?.status||'active'}><option value="active">Actif</option><option value="inactive">Inactif</option></select></label><input type="hidden" name="stock" value={x?.stock||0}/><div className="rounded-lg bg-emerald-50 p-3"><span className="label">Stock initial</span><b className="text-emerald-800">{x?.stock||0} unité(s)</b><p className="text-xs text-emerald-700">Les quantités sont ajustées depuis Gestion du stock.</p></div><Field label="Image URL facultative" name="photo_path" value={x?.photo_path}/><label className="sm:col-span-2"><span className="label">Description</span><textarea className="input" name="description" rows={3} defaultValue={x?.description||''}/></label><label className="sm:col-span-2"><span className="label">Photo locale JPG, PNG ou WebP</span><input className="input" name="photo" type="file" accept="image/jpeg,image/png,image/webp"/></label><div className="sm:col-span-2 rounded-lg bg-slate-50 p-3"><span className="label">Nouvelle catégorie rapide</span><div className="flex gap-2"><input className="input" value={categoryName} onChange={e=>setCategoryName(e.target.value)} placeholder="Nom de la catégorie"/><button type="button" className="btn-secondary" onClick={addCategory}>Ajouter</button></div>{catError&&<p className="mt-1 text-xs text-red-600">{catError}</p>}</div></>}
  const x=row as User|null;return <><Field label="Nom complet" name="full_name" required value={x?.full_name}/><Field label="Email" name="email" type="email" required value={x?.email}/><Field label={x?'Nouveau mot de passe (optionnel)':'Mot de passe'} name="password" type="password" required={!x}/><label><span className="label">Rôle</span><select className="input" name="role" defaultValue={x?.role||'client'}><option value="admin">Admin</option><option value="achats">Achats</option><option value="client">Client</option></select></label><p className="sm:col-span-2 rounded-lg bg-blue-50 p-3 text-xs text-blue-700">Pour le rôle Client, la fiche client est créée ou retrouvée automatiquement à partir de l'email.</p>{x&&<input type="hidden" name="is_active" value={String(x.is_active)}/>}</>
}

function Actions({row,onEdit,onDelete,onToggle}:{row:Row;onEdit:(x:Row)=>void;onDelete:(x:Row)=>void;onToggle:(x:Row)=>void}) { return <div className="flex gap-1"><button className="rounded p-2 text-blue-700 hover:bg-blue-50" title="Modifier" onClick={()=>onEdit(row)}><Edit3 size={17}/></button><button className="rounded p-2 text-amber-700 hover:bg-amber-50" title="Activer ou désactiver" onClick={()=>onToggle(row)}><Power size={17}/></button><button className="rounded p-2 text-red-700 hover:bg-red-50" title="Supprimer" onClick={()=>onDelete(row)}><Trash2 size={17}/></button></div> }
function UserActions({user,onEdit,onDelete,onApprove,onReject,onDeactivate}:{user:User;onEdit:(x:Row)=>void;onDelete:(x:Row)=>void;onApprove:(x:User)=>void;onReject:(x:User)=>void;onDeactivate:(x:User)=>void}){return <div className="flex flex-wrap gap-1"><button className="rounded p-2 text-blue-700 hover:bg-blue-50" title="Modifier" onClick={()=>onEdit(user)}><Edit3 size={17}/></button>{(user.approval_status==='pending'||!user.is_active)&&user.approval_status!=='rejected'&&<button className="rounded p-2 text-emerald-700 hover:bg-emerald-50" title="Approuver" onClick={()=>onApprove(user)}><CheckCircle2 size={18}/></button>}{user.approval_status==='pending'&&<button className="rounded p-2 text-red-700 hover:bg-red-50" title="Refuser" onClick={()=>onReject(user)}><XCircle size={18}/></button>}{user.is_active&&<button className="rounded p-2 text-amber-700 hover:bg-amber-50" title="Désactiver" onClick={()=>onDeactivate(user)}><Power size={17}/></button>}<button className="rounded p-2 text-red-700 hover:bg-red-50" title="Supprimer" onClick={()=>onDelete(user)}><Trash2 size={17}/></button></div>}
function ResourceTable({kind,rows,categories,canEdit,onEdit,onDelete,onToggle,onApprove,onReject,onDeactivate}:{kind:Kind;rows:Row[];categories:Category[];canEdit:boolean;onEdit:(x:Row)=>void;onDelete:(x:Row)=>void;onToggle:(x:Row)=>void;onApprove:(x:User)=>void;onReject:(x:User)=>void;onDeactivate:(x:User)=>void}) {
  if(kind==='clients')return <table><thead><tr><th>Client</th><th>ICE / RC</th><th>Ville</th><th>Contact</th><th>Statut</th><th>Actions</th></tr></thead><tbody>{(rows as Client[]).map(x=><tr key={x.id}><td><b>{x.name}</b><div className="text-xs text-slate-500">{x.company_name||'—'}</div></td><td>{x.ice||'—'}<div className="text-xs">RC {x.rc||'—'}</div></td><td>{x.city||'—'}</td><td>{x.phone||'—'}<div className="text-xs">{x.email}</div></td><td><Badge tone={x.status==='active'?'green':'gray'}>{x.status==='active'?'Actif':'Inactif'}</Badge></td><td>{canEdit&&<Actions row={x} onEdit={onEdit} onDelete={onDelete} onToggle={onToggle}/>}</td></tr>)}</tbody></table>
  if(kind==='products')return <table><thead><tr><th>Produit</th><th>Référence</th><th>Catégorie</th><th>Prix de vente</th><th>Stock actuel</th><th>Seuil minimum</th><th>État du stock</th><th>Statut</th><th>Actions</th></tr></thead><tbody>{(rows as Product[]).map(x=>{const stockState=x.stock===0?['Rupture','red'] as const:x.stock<=x.minimum_stock?['Stock faible','red'] as const:['Disponible','green'] as const;return <tr key={x.id}><td><div className="flex items-center gap-3">{x.photo_path&&<img src={x.photo_path} alt="" className="h-9 w-9 rounded object-cover"/>}<span className="font-semibold">{x.name}</span></div></td><td className="font-mono text-xs">{x.reference}</td><td>{categories.find(c=>c.id===x.category_id)?.name||'—'}</td><td>{Number(x.price).toLocaleString('fr-MA')} MAD</td><td className="font-bold">{x.stock}</td><td>{x.minimum_stock}</td><td><Badge tone={stockState[1]}>{stockState[0]}</Badge></td><td><Badge tone={x.status==='active'?'green':'gray'}>{x.status==='active'?'Actif':'Inactif'}</Badge></td><td><div className="flex flex-wrap gap-1">{canEdit&&<Actions row={x} onEdit={onEdit} onDelete={onDelete} onToggle={onToggle}/>}<button className="btn-secondary px-2 py-1 text-xs" onClick={()=>window.location.assign(`/stock/movements?product_id=${x.id}`)}>Voir les mouvements</button></div></td></tr>})}</tbody></table>
  return <table><thead><tr><th>Utilisateur</th><th>Contact client</th><th>Rôle</th><th>Inscription</th><th>Statut</th><th>Actions</th></tr></thead><tbody>{(rows as User[]).map(x=><tr key={x.id}><td><div className="font-semibold">{x.full_name}</div><div className="text-xs text-slate-500">{x.email}</div></td><td>{x.client?<><div>{x.client.company_name||x.client.name}</div><div className="text-xs text-slate-500">{x.client.phone||'Sans téléphone'} · {x.client.city||'Ville non renseignée'}</div></>:<span className="text-slate-400">—</span>}</td><td className="capitalize">{x.role}</td><td>{new Date(x.created_at).toLocaleDateString('fr-MA')}</td><td>{x.approval_status==='pending'?<Badge tone="blue">En attente</Badge>:x.approval_status==='rejected'?<Badge tone="red">Refusé</Badge>:x.is_active?<Badge tone="green">Actif</Badge>:<Badge tone="gray">Désactivé</Badge>}</td><td>{canEdit&&<UserActions user={x} onEdit={onEdit} onDelete={onDelete} onApprove={onApprove} onReject={onReject} onDeactivate={onDeactivate}/>}</td></tr>)}</tbody></table>
}
