/** Tableau de stock : synthèse, historique traçable et corrections exceptionnelles. */
import { useMemo, useState, type FormEvent } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { AlertTriangle, ArrowDownToLine, ArrowUpFromLine, Boxes, PackageCheck, PackageX, SlidersHorizontal } from 'lucide-react'
import { useNavigate, useSearchParams } from 'react-router-dom'
import { api } from '../lib/api'
import type { Product, StockMovement, StockMovementKind } from '../types'
import { Badge, Empty, Loading, Modal, Notice, PageHeader } from '../components/UI'

const message=(error:any)=>typeof error.response?.data?.detail==='string'?error.response.data.detail:'Une erreur est survenue'
const labels:Record<StockMovementKind,string>={ENTREE_ACHAT:'Entrée achat',SORTIE_COMMANDE_CLIENT:'Sortie commande client',AJUSTEMENT_POSITIF:'Ajustement positif',AJUSTEMENT_NEGATIF:'Ajustement négatif',RETOUR_CLIENT:'Retour client',PRODUIT_ENDOMMAGE:'Produit endommagé',INVENTAIRE:'Inventaire'}
const origins:Record<string,string>={purchase:'Achat fournisseur',customer_order:'Commande client',manual_adjustment:'Ajustement manuel',inventory:'Inventaire'}

export default function Stock(){
  const [searchParams]=useSearchParams(),navigate=useNavigate(),qc=useQueryClient()
  const [modal,setModal]=useState(false),[q,setQ]=useState(''),[kind,setKind]=useState(''),[productId,setProductId]=useState(searchParams.get('product_id')||''),[date,setDate]=useState(''),[userId,setUserId]=useState(''),[origin,setOrigin]=useState(''),[notice,setNotice]=useState<{message:string;type:'success'|'error'}|null>(null)
  const products=useQuery({queryKey:['products-stock'],queryFn:()=>api.get<Product[]>('/products').then(r=>r.data)})
  const movements=useQuery({queryKey:['movements',q,kind,productId,date,userId,origin],queryFn:()=>api.get<StockMovement[]>('/stock/movements',{params:{q:q||undefined,movement_type:kind||undefined,product_id:productId||undefined,date:date||undefined,user_id:userId||undefined,source_type:origin||undefined}}).then(r=>r.data)})
  const save=useMutation({mutationFn:(body:unknown)=>api.post('/stock/movements',body),onSuccess:()=>{void qc.invalidateQueries();setModal(false);setNotice({message:'Ajustement de stock enregistré.',type:'success'})},onError:error=>setNotice({message:message(error),type:'error'})})
  const summary=useMemo(()=>{const list=products.data||[],month=new Date().toISOString().slice(0,7),moves=movements.data||[];return {products:list.length,total:list.reduce((sum,p)=>sum+p.stock,0),low:list.filter(p=>p.stock>0&&p.stock<=p.minimum_stock).length,out:list.filter(p=>p.stock===0).length,entries:moves.filter(m=>m.created_at.slice(0,7)===month&&m.type==='in').reduce((s,m)=>s+m.quantity,0),exits:moves.filter(m=>m.created_at.slice(0,7)===month&&m.type==='out').reduce((s,m)=>s+m.quantity,0)}},[products.data,movements.data])
  const cards=[['Produits',summary.products,Boxes],['Quantité totale',summary.total,PackageCheck],['Stock faible',summary.low,AlertTriangle],['Ruptures',summary.out,PackageX],['Entrées du mois',summary.entries,ArrowDownToLine],['Sorties du mois',summary.exits,ArrowUpFromLine]] as const
  return <><PageHeader title="Gestion du stock" subtitle="Quantités disponibles, alertes et traçabilité des mouvements" action={<button className="btn-primary" onClick={()=>setModal(true)}><SlidersHorizontal size={18}/>Ajuster le stock</button>}/>
    <div className="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-6">{cards.map(([label,value,Icon])=><div className="card p-4" key={label}><Icon className="mb-3 text-emerald-600" size={22}/><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</p><strong className="mt-1 block text-2xl text-navy-900">{value}</strong></div>)}</div>
    <div className="card mb-5 grid gap-3 p-4 sm:grid-cols-2 xl:grid-cols-6"><input className="input" value={q} onChange={e=>setQ(e.target.value)} placeholder="Référence ou motif…"/><select className="input" value={productId} onChange={e=>setProductId(e.target.value)}><option value="">Tous les produits</option>{products.data?.map(p=><option key={p.id} value={p.id}>{p.reference} — {p.name}</option>)}</select><select className="input" value={kind} onChange={e=>setKind(e.target.value)}><option value="">Tous les types</option>{Object.entries(labels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select><input className="input" type="date" value={date} onChange={e=>setDate(e.target.value)}/><input className="input" type="number" min="1" value={userId} onChange={e=>setUserId(e.target.value)} placeholder="ID utilisateur"/><select className="input" value={origin} onChange={e=>setOrigin(e.target.value)}><option value="">Toutes les origines</option>{Object.entries(origins).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></div>
    {movements.isLoading||products.isLoading?<Loading/>:<div className="table-wrap">{movements.data?.length?<table><thead><tr><th>Date et heure</th><th>Produit</th><th>Référence</th><th>Type</th><th>Quantité</th><th>Ancien</th><th>Nouveau</th><th>Origine</th><th>Document</th><th>Utilisateur</th><th>Commentaire</th></tr></thead><tbody>{movements.data.map(m=>{const p=products.data?.find(x=>x.id===m.product_id);return <tr key={m.id}><td>{new Date(m.created_at).toLocaleString('fr-MA')}</td><td className="font-semibold">{p?.name||`Produit #${m.product_id}`}</td><td className="font-mono text-xs">{p?.reference||'—'}</td><td><Badge tone={m.type==='in'?'green':m.type==='out'?'red':'blue'}>{labels[m.movement_type]||m.movement_type}</Badge></td><td>{m.quantity}</td><td>{m.previous_stock??'—'}</td><td className="font-bold">{m.new_stock??'—'}</td><td>{origins[m.reference_type||'']||m.reference_type||'—'}</td><td>{m.reference_type==='purchase'?<button className="text-emerald-700 underline" onClick={()=>navigate(`/purchases?purchase_id=${m.reference_id}`)}>Voir l’achat {m.reference}</button>:m.reference_type==='customer_order'?<button className="text-emerald-700 underline" onClick={()=>navigate(`/customer-orders?order_id=${m.reference_id}`)}>Voir la commande {m.reference}</button>:m.reference||'—'}</td><td>{m.user_id?`#${m.user_id}`:'Système'}</td><td>{m.comment||m.reason||'—'}</td></tr>})}</tbody></table>:<Empty text="Aucun mouvement de stock n’a encore été enregistré. Les mouvements apparaîtront après une réception d’achat, une validation de commande client ou un ajustement manuel."/>}</div>}
    {modal&&<Adjustment products={products.data||[]} busy={save.isPending} onClose={()=>setModal(false)} onSubmit={body=>save.mutate(body)}/>} {notice&&<Notice {...notice} onClose={()=>setNotice(null)}/>}</>
}

function Adjustment({products,busy,onClose,onSubmit}:{products:Product[];busy:boolean;onClose:()=>void;onSubmit:(body:unknown)=>void}){
  const [productId,setProductId]=useState(products[0]?.id||0),[kind,setKind]=useState<StockMovementKind>('AJUSTEMENT_POSITIF'),[quantity,setQuantity]=useState(1),[confirm,setConfirm]=useState(false),[reason,setReason]=useState(''),[comment,setComment]=useState('')
  const product=products.find(p=>p.id===productId),current=product?.stock||0,next=kind==='INVENTAIRE'?quantity:kind==='AJUSTEMENT_POSITIF'?current+quantity:current-quantity
  const submit=(event:FormEvent)=>{event.preventDefault();if(!confirm)return;onSubmit({product_id:productId,movement_type:kind,quantity,reason,comment:comment||null})}
  return <Modal title="Ajuster le stock" onClose={onClose}><form className="space-y-4" onSubmit={submit}><p className="rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm text-amber-800">Les entrées d’achats et les sorties de commandes clients sont enregistrées automatiquement. Utilisez cet ajustement uniquement pour une correction exceptionnelle.</p><label><span className="label">Produit obligatoire</span><select className="input" value={productId} onChange={e=>setProductId(Number(e.target.value))} required>{products.map(p=><option value={p.id} key={p.id}>{p.reference} — {p.name}</option>)}</select></label><label><span className="label">Type d’ajustement</span><select className="input" value={kind} onChange={e=>setKind(e.target.value as StockMovementKind)}><option value="AJUSTEMENT_POSITIF">Ajustement positif</option><option value="AJUSTEMENT_NEGATIF">Ajustement négatif</option><option value="INVENTAIRE">Inventaire (stock final)</option><option value="PRODUIT_ENDOMMAGE">Produit endommagé</option></select></label><label><span className="label">Quantité {kind==='INVENTAIRE'?'finale':''}</span><input className="input" type="number" min="1" value={quantity} onChange={e=>setQuantity(Number(e.target.value))} required/></label><div className="grid grid-cols-2 gap-3"><div className="rounded-xl bg-slate-50 p-3"><span className="text-xs text-slate-500">Stock actuel</span><b className="block text-xl">{current}</b></div><div className={`rounded-xl p-3 ${next<0?'bg-red-50 text-red-700':'bg-emerald-50 text-emerald-800'}`}><span className="text-xs">Nouveau stock</span><b className="block text-xl">{next}</b></div></div><label><span className="label">Motif obligatoire</span><input className="input" value={reason} onChange={e=>setReason(e.target.value)} minLength={2} required/></label><label><span className="label">Commentaire</span><textarea className="input" rows={3} value={comment} onChange={e=>setComment(e.target.value)}/></label><label className="flex items-start gap-2 text-sm"><input className="mt-1" type="checkbox" checked={confirm} onChange={e=>setConfirm(e.target.checked)}/><span>Je confirme cette correction exceptionnelle et le nouveau stock calculé.</span></label><button className="btn-primary w-full" disabled={busy||!confirm||next<0}>{busy?'Enregistrement…':'Confirmer l’ajustement'}</button></form></Modal>
}
