// Contrats TypeScript alignés sur les schémas FastAPI.
export type Role = 'admin' | 'achats' | 'client'
export type ApprovalStatus='pending'|'approved'|'rejected'
export interface UserClientSummary { id:number; name:string; company_name?:string; phone?:string; city?:string; status:string }
export interface User { id:number; full_name:string; email:string; role:Role; is_active:boolean; created_at:string; client_id?:number; approval_status:ApprovalStatus; approved_at?:string; approved_by?:number; client?:UserClientSummary }
export interface Client { id:number; name:string; company_name?:string; ice?:string; rc?:string; address?:string; city?:string; phone?:string; email?:string; status:string; created_at:string }
export interface Supplier { id:number; name:string; company_name?:string; ice?:string; rc?:string; email?:string; phone?:string; address?:string; city?:string; primary_contact?:string; status:string; created_at:string; updated_at:string }
export interface Category { id:number; name:string }
export interface Product { id:number; reference:string; name:string; commercial_name?:string; active_ingredient?:string; description?:string; price:number; default_purchase_price?:number; photo_path?:string; category_id?:number; stock:number; minimum_stock:number; barcode?:string; status:string; laboratory?:string; dosage?:string; pharmaceutical_form?:string; packaging?:string; created_at:string }
export interface PurchaseLine { id:number; product_id:number; quantity:number; received_quantity:number; unit_price:number; discount:number; tax_rate:number; line_total:number; tax_amount:number; total_amount:number }
export interface PurchasePrice { product_id:number; supplier_id?:number; purchase_price:number|null; source:'supplier_product'|'last_purchase'|'product_default'|'product_existing_price'|'unavailable' }
export interface Purchase { id:number; number:string; supplier_id?:number; supplier?:Supplier; status:string; purchase_date:string; expected_delivery_date?:string; supplier_confirmed_delivery_date?:string; actual_reception_date?:string; supplier_confirmation_reference?:string; supplier_confirmation_contact?:string; supplier_confirmation_comment?:string; supplier_accepted_at?:string; supplier_acceptance_comment?:string; supplier_acceptance_reference?:string; supplier_accepted_by?:number; received_at?:string; reception_comment?:string; subtotal:number; tax_amount:number; total:number; notes?:string; created_by?:number; received_by?:number; created_at:string; lines:PurchaseLine[] }
export type StockMovementKind='ENTREE_ACHAT'|'SORTIE_COMMANDE_CLIENT'|'AJUSTEMENT_POSITIF'|'AJUSTEMENT_NEGATIF'|'RETOUR_CLIENT'|'PRODUIT_ENDOMMAGE'|'INVENTAIRE'
export interface StockMovement { id:number; product_id:number; type:'in'|'out'|'adjustment'; movement_type:StockMovementKind; quantity:number; reason:string; reference?:string; user_id?:number; previous_stock?:number; new_stock?:number; reference_type?:string; reference_id?:number; comment?:string; created_at:string }
export interface DashboardOrder { id:number; order_number:string; client_name:string; created_at:string; total_amount:number; status:OrderStatus; next_action?:string }
export interface DashboardData { products_count:number; clients_count:number; total_stock:number; low_stock_count:number; recent_purchases:Purchase[]; total_purchases:number; purchases_in_preparation:number; purchases_sent:number; purchases_confirmed:number; purchases_received:number; receptions_today:number; total_orders:number; pending_orders:number; approved_orders:number; approved_today:number; in_preparation:number; shipped_orders:number; delivered_orders:number; rejected_orders:number; approved_amount:number; orders_to_process:DashboardOrder[]; recent_orders:DashboardOrder[] }
export interface Audit { id:number; user_id?:number; action:string; entity:string; entity_id?:string; details?:string; ip_address?:string; created_at:string }
export interface Company { id:number; company_name:string; address?:string; phone?:string; email?:string; logo_path?:string }
export type OrderStatus = 'draft'|'pending'|'approved'|'rejected'|'in_preparation'|'shipped'|'delivered'|'cancelled'|'confirmed'|'prepared'
export interface CustomerOrderLine { id:number; product_id:number; product_name:string; product_reference:string; quantity:number; unit_price:number; line_total:number }
export interface CustomerOrder { id:number; number:string; client_id:number; user_id?:number; status:OrderStatus; total:number; created_at:string; updated_at:string; approved_at?:string; approved_by?:number; rejected_at?:string; rejected_by?:number; rejection_reason?:string; purchase_comment?:string; client?:Client; lines:CustomerOrderLine[] }
