from app.models.entities import Role

READ_PERMISSIONS={
 Role.ADMIN:{"PRODUCT_SEARCH","PRODUCT_STOCK","LOW_STOCK_PRODUCTS","ACTIVE_SUPPLIERS","PENDING_CUSTOMER_ORDERS","PURCHASES_TO_RECEIVE","DASHBOARD_SUMMARY","ORDER_STATUS","NAVIGATE"},
 Role.PURCHASES:{"PRODUCT_SEARCH","PRODUCT_STOCK","LOW_STOCK_PRODUCTS","ACTIVE_SUPPLIERS","PENDING_CUSTOMER_ORDERS","PURCHASES_TO_RECEIVE","DASHBOARD_SUMMARY","ORDER_STATUS","NAVIGATE"},
 Role.CLIENT:{"PRODUCT_SEARCH","PRODUCT_STOCK","MY_ORDERS","ORDER_STATUS","NAVIGATE"},
}
ACTION_PERMISSIONS={Role.ADMIN:{"RESTOCK_PROPOSAL","CREATE_PURCHASE_DRAFT","GENERATE_REPORT"},Role.PURCHASES:{"RESTOCK_PROPOSAL","CREATE_PURCHASE_DRAFT","GENERATE_REPORT"},Role.CLIENT:set()}

def allowed(role:Role,intent:str)->bool:return intent in READ_PERMISSIONS.get(role,set()) or intent in ACTION_PERMISSIONS.get(role,set())
